### ISSUE TITLE
Confusion with type in `launch.json`

### ISSUE THREAD

**Issue by bombsimon** [Whitebrim/VSCode-PlaydateTemplate#1]
Thanks for this template, really helpful to get up and running!

Now that Windows is supported, I saw an [issue](https://github.com/orta/vscode-playdate/issues/12) in the [`vscode-playdate`](https://github.com/orta/vscode-playdate) plugin repository from a user using both this template _and_ installed the `vscode-playdate` plugin. Since the plugin registers the debug type as `playdate`, every user that uses this template and the plugin will launch the simulator twice (or in this case get an error since no output is configured).

Since you have a bunch of tasks configured, including running scripts to shut down running instances, I think they might be worth keeping. If so, just using a different [`type`](https://github.com/Whitebrim/VSCode-PlaydateTemplate/blob/f862be2690928ddc66dc9dfb64203179676f2a57/.vscode/launch.json#L5) than `playdate` would avoid confusion and issues. As far as I know it will still run all the `preLaunchTask` even if the type is unknown so something like `playdate-template` should work. 

Another alternative could be to just add [Orta.playdate](https://marketplace.visualstudio.com/items?itemName=Orta.playdate) in `extensions.json` but that won't play nice with your tasks so they would become obsolete.

**Comment by Whitebrim** [comment]
Is it what you want?
https://github.com/Whitebrim/VSCode-PlaydateTemplate/pull/3/files

**Comment by bombsimon** [comment]
If it still works for you that would be great! I won't be able to test this on a Windows machine until later tonight if you want me to confirm as well but! Thanks!

**Comment by Whitebrim** [comment]
> I won't be able to test this on a Windows machine until later tonight if you want me to confirm as well but! Thanks!

Same for me...

**Comment by bombsimon** [comment]
Tried this now and apparently I was wrong, it's not possible to use a type that does not exist. Using this it launches the simulator but also get a popup saying `Configure debug type 'playdate-template' is not supported.` I tried to set it to `node` instead which is built in but that launches a node debugger that does nothing and needs manual stopping. On the other hand, uninstalling the playdate plugin and keeping it as it is now yields the same error but for `playdate` since it's no longer installed so maybe `node` isn't the worst.

One thing I thought of was that your template has a PowerShell script and assumes the user is on Windows so maybe it's not a bad idea to suggest and assume users install the [PowerShell Plugin](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell). If that's installed you can set the type to `"PowerShell"` and just call something that immediately terminates to exit out of the debugger but keep the simulator running (since it's launched through the task). I'm thinking something like this:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "PowerShell",
            "request": "launch",
            "script": "Write-Host Simulator Started",
            "name": "Build and Run (Simulator)",
            "preLaunchTask": "Build and Run (Simulator)"
        }
    ]
}
```

**Comment by Whitebrim** [comment]
@bombsimon 
Seems like without launch.json this template still is working and building project.
https://github.com/Whitebrim/VSCode-PlaydateTemplate/commit/7c1f5a5841ede427374c451a12f2559be637e91f

**Comment by bombsimon** [comment]
Nice, thanks! Didn't know if you were OK not using the debugger but this is for sure the easiest way, just running the build task instead of the debugger should work fine!

Thanks for looking into this and helping sorting out the confusion! 💯
