### ISSUE TITLE
Build and Run .ps1 script doesn't work

### ISSUE THREAD

**Issue by pedromvnreis** [Whitebrim/VSCode-PlaydateTemplate#10]
Whenever I run the .ps1 file, a Playdate simulator window opens running Launcher.pdx and I can't drag and drop a .pdx folder into it like usual and instead have to open it through File > Open...

I tested running the script with both PowerShell 5 and PowerShell 7 but the issue remained.

**Comment by chills-hub** [comment]
Yeah I'd like to second this, all paths seem correct and none of the env variables are duplicated, and VS Code isn't showing any errors in the output

**Comment by Whitebrim** [comment]
Strangelly, it didn't work for me once on first launch, then it works fine.
Please let me know more delails @pedromvnreis @chills-hub
