### ISSUE TITLE
Maybe not obvious that developers need to change pdxinfo

### ISSUE THREAD

**Issue by daprice** [Whitebrim/VSCode-PlaydateTemplate#11]
I’ve run into more than one published game with the bundle ID “com.organization.package”, and some even show up as “Template by You”. Just a suggestion, but the instructions in the readme should include changing those.

It might even be a good idea to leave the bundle ID out of the template. If a dev forgets to set their bundle ID, it’s probably better if the game fails to sideload (missing bundle ID) than to have a bundle ID collision.

**Comment by Whitebrim** [comment]
Haha, sure, I'll work on this issue~

**Comment by Whitebrim** [comment]
What do you think? https://github.com/Whitebrim/VSCode-PlaydateTemplate/blob/master/README.md

**Comment by daprice** [comment]
👍🏻Looks good to me, assuming people read it 🤷🏻‍♂️
