### ISSUE TITLE
ADD_ENV_VARIABLE.cmd assumes My Documents location

### ISSUE THREAD

**Issue by dustdustinthewind** [Whitebrim/VSCode-PlaydateTemplate#2]
I have My Documents set up to be on my F: drive, rather than the windows-install C: drive.

`set SDKPATH="%userprofile%\Documents\PlaydateSDK` on line 3 of ADD_ENV_VARIABLE.cmd does not grab the right documents in my case, it's looking for `C:[user]\Documents` instead of `F:My Documents`

The PlaydateSDK installation used the correct location, the F: location. The mismatch between Playdate and this program means invalid locations are being used for the env vars for users like me, causing errors when building.

The documents address to use instead can be found [here](https://support.microsoft.com/en-us/topic/configuration-of-the-my-documents-folder-dfd9a90d-8f80-18d6-e7cc-f1566fc3b10b) (`HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders` name: `Personal`).

Replacing line 3 with my location and re-running the program didn't fix the issue for me. I got a different error from powershell about the address I gave it (idk if being on a different drive has anything to do with it). Re-running the program also kept adding to the Path env variable, it doesn't check for dupes it seems.

I did the following to fix the variables instead. For users in my situation here's how you fix the bad paths:

Copy your Playdate SDK folder address. ( "...\PlaydateSDK" )
Go to start menu, search for "Environment Variable" click on "Edit the system environment variables"
Click on "Environment Variables..."
Look under "System variables" for "PLAYDATE_SDK_PATH" and click it. Then click "Edit"
Replace the "Variable value" with the Playdate SDK folder address you copied earlier. Click "OK"
Under "System variables" again, look for "Path". Click "Edit"
Replace any and all instances of the bad Playdate SDK address with the SDK folder address you copied earlier BUT add "\bin" to the end ( "...\PlaydateSDK\bin" ).
Click OKs until you're out. Try building again.

**Comment by Whitebrim** [comment]
Yes, .cmd file don't rewrite envvar for PATH if it already exist, but PLAYDATE_SDK_PATH var should be rewritten.
Maybe your problem was missing / in `F:/My Documents`?
I'll look into link you provided and will try to find a solution. Thank you for the issue.

**Comment by samuelalmeidadev** [comment]
Not exactly the same issue but still related to the "ADD_ENV_VARIABLE.cmd" file. When running it, an error would come up on the SETX usage saying: "Invalid syntax. Default option is not allowed more than '2' time(s)." My SDK installation is the default one in the C drive so not sure why it was failing but I was able to unblock myself by following @FlyingRabidUnicornPig suggestion of in my case adding the environment variables manually as I had none set.

**Comment by Whitebrim** [comment]
@FlyingRabidUnicornPig @samuelalmeidadev 
Try latest version please

**Comment by Whitebrim** [comment]
This commit 11f75429a0cc2b61938271887e52154ab68d6503 should be finally working
@FlyingRabidUnicornPig
