### ISSUE TITLE
VSCode does not work "Run build task"

### ISSUE THREAD

**Issue by BrendowPaolillo-dev** [Whitebrim/VSCode-PlaydateTemplate#21]
I've followed all the steps described in README.md, for Windows. Everything it's working well, the pdc command, the playdate sim, only my VSCode wich does not recognize the build task. This is what it showing when I try to run build task:
![image](https://github.com/Whitebrim/VSCode-PlaydateTemplate/assets/7331149/6e06dad6-343e-4afd-8383-d8947b054a05)

Any solution?

**Comment by Whitebrim** [comment]
Do you have recommended plugins installed?

**Comment by BrendowPaolillo-dev** [comment]
Yes
![image](https://github.com/Whitebrim/VSCode-PlaydateTemplate/assets/7331149/e135ff3f-4c7b-42a4-afb4-a30c1240aada)

**Comment by Whitebrim** [comment]
@BrendowPaolillo-dev build tasks are located in this repo in .vscode/tasks.json and this folder (.vscode) should hold the same files in your machine (in .vscode folder). And you need to open VSCode from root folder (RMB -> Open VSCode here), not manually add files.
