### ISSUE TITLE
Build Task Speed

### ISSUE THREAD

**Issue by redmoe** [Whitebrim/VSCode-PlaydateTemplate#5]
Hi there. Thank you for the program and tutorial! Was wondering if it'd be possible to speed up the task.json? Right now it's taking about 8 seconds to complete for me.

I notice it closes and then reopens the simulator, which seems to take a large chunk of the time. Would it be possible to have it check for an existing simulator and run the program from that one instead, and only open a new instance if there is none?

Also if there was a way improve the deleting of files? Right now that takes at least 2 seconds which seems excessive.

I'm personally looking into modifying mine and if I find an improvement will be sure to share, but was wondering if had any thoughts on the matter. Thanks!

**Comment by kmcginn** [comment]
I suspect a lot of the time is being taken up by whatever VS Code does to move between tasks. The actual commands themselves move pretty quickly.

I did notice that about a month after this template repo removed Orta's Playdate extension as a recommended extension, that extension was [updated to include Windows support](https://github.com/orta/vscode-playdate/pull/11). When I run the build through that extension's command, it is a LOT faster. Maybe re-adding the extension as a suggestion and encouraging the use of that command could help?

**Comment by Whitebrim** [comment]
I'll try combine all build tasks into one PowerShell script

**Comment by Whitebrim** [comment]
@redmoe try this version please 1b115276492425cf9b649ed4613332c804db6b20

**Comment by redmoe** [comment]
Much better, thank you! Getting about 3 seconds to build. I've been using Nova in the interim which takes about a second, however grateful to have a pc option to work with. Thanks for the update!
