### ISSUE TITLE
Unnecessary Admin?

### ISSUE THREAD

**Issue by kmcginn** [Whitebrim/VSCode-PlaydateTemplate#6]
I don't think it is strictly necessary to run VS Code as Admin to get this whole process working. I've been able to successfully build from a non-admin VS Code session using this template.

If the problem is with the closeSim.ps1 script, I think setting the PowerShell execution policy to [RemoteSigned](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7.2#remotesigned) will allow it to run the script after it has been Unblocked. The commands in the script itself don't seem to require Admin in order to work.

I'd be curious to hear why it may have been necessary in the past!

**Comment by Whitebrim** [comment]
I simply didn't know about PowerShell execution policy, let me change readme

**Comment by Whitebrim** [comment]
51c7d60a07902f3ad7b6df5603cdcf6fec9b7d36
