### ISSUE TITLE
Build and Run resulting in error

### ISSUE THREAD

**Issue by SenseiRAM** [Whitebrim/VSCode-PlaydateTemplate#7]
This could very much be a configuration error on my part, but I cannot get the Build and Run script to execute properly when I invoke it in VS Code. I've followed the readme exactly, as far as I can tell. Below is the command and the output I'm seeing.

`> Executing task: & 'C:\Users\richa\Documents\PlayDate_Template\VSCode-PlaydateTemplate-master\Build and Run (Simulator).ps1' -build 'C:\Users\richa\Documents\PlayDate_Template\VSCode-PlaydateTemplate-master\builds' -source 'C:\Users\richa\Documents\PlayDate_Template\VSCode-PlaydateTemplate-master\source' -name 'VSCode-PlaydateTemplate-master' <`

```
/usr/bin/bash: -c: line 0: syntax error near unexpected token `&'
/usr/bin/bash: -c: line 0: `& 'C:\Users\richa\Documents\PlayDate_Template\VSCode-PlaydateTemplate-master\Build and Run (Simulator).ps1' -build 'C:\Users\richa\Documents\PlayDate_Template\VSCode-PlaydateTemplate-master\builds' -source 'C:\Users\richa\Documents\PlayDate_Template\VSCode-PlaydateTemplate-master\source' -name 'VSCode-PlaydateTemplate-master''
The terminal process "C:\Program Files\Git\bin\bash.exe '--login', '-c', '& 'C:\Users\richa\Documents\PlayDate_Template\VSCode-PlaydateTemplate-master\Build and Run (Simulator).ps1' -build 'C:\Users\richa\Documents\PlayDate_Template\VSCode-PlaydateTemplate-master\builds' -source 'C:\Users\richa\Documents\PlayDate_Template\VSCode-PlaydateTemplate-master\source' -name 'VSCode-PlaydateTemplate-master''" terminated with exit code: 1.
```

**Comment by Whitebrim** [comment]
VS Code should run this command in Windows PowerShell as default...

**Comment by SenseiRAM** [comment]
Oy, that was it. My default terminal was set to Git Bash. Working now. Thanks!
